myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sgmaq.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sgmaq/urls.py
from django.urls import path
from . import views
from django.contrib import admin
from django.conf import settings  # new
from django.urls import path, include  # new
from django.conf.urls.static import static  # new

urlpatterns = [    
    path('', views.index, name="index"),
    path('about/', views.about, name="about"),
    path('signin/', views.signin, name="signin"),
    path('signup/', views.signup, name="signup"),
    path('logout/', views.signout, name="logout"),

    path('tasks/', views.tasks, name="tasks"),
    path('tasks/task_search', views.task_search, name="task_search"),
    path('task_detail/<int:task_id>', views.task_detail, name="task_detail"),
    path('tasks_history/', views.tasks_history, name="tasks_history"),

    path('upload/', views.upload_file, name='upload_file'),

    path('task_delivery/<int:task_id>', views.task_delivery, name="task_delivery"),
    path('tasks/<int:task_id>/complete', views.complete_task, name="complete_task"),
    path('upload_image/<int:task_id>/', views.upload_image, name='upload_image'),

    path('task_manager_pending/', views.task_manager_pending, name="task_manager_pending"),
    path('task_manager_approval/<int:task_id>', views.task_manager_approval, name="task_manager_approval"), 
    path('task_manager_denial/<int:task_id>/', views.task_manager_denial, name="task_manager_denial"),  
    path('task_manager_client_pending/', views.task_manager_client_pending, name="task_manager_client_pending"),  

    path('task_client_pending/', views.task_client_pending, name="task_client_pending"),
    path('task_client_approval/<int:task_id>/', views.task_client_approval, name="task_client_approval"),    
    path('task_client_denial/<int:task_id>/', views.task_client_denial, name="task_client_denial"),    

    path('dashboard/', views.dashboard, name="dashboard"),

    path('download/', views.download_page, name='download_page'),
    path('download_pdf/', views.generate_pdf, name='generate_pdf'),
]  


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) #new

sgmaq/models.py
from django.db import models
from django.contrib.auth.models import User


class Project(models.Model):
    name = models.CharField(max_length=200)
    def __str__(self):
        return self.name
    
class Client(models.Model):
    name = models.CharField(max_length=100)
    address = models.CharField(max_length=100)
    phone = models.CharField(max_length=100)
    email = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name
    
class CarBrand(models.Model):
    brandname = models.CharField(max_length=100)

    def __str__(self):
        return self.brandname

class CarModel(models.Model):
    model = models.CharField(max_length=100)
    brandname = models.ForeignKey(CarBrand, on_delete=models.CASCADE)

    def __str__(self):
        return self.model
    

class ChangeType(models.Model):
    changetype = models.CharField(max_length=100)

    def __str__(self):
        return self.changetype
    

class ChangeReason(models.Model):
    changereason = models.CharField(max_length=100)
    changetype = models.ForeignKey(ChangeType, on_delete=models.CASCADE)

    def __str__(self):
        return self.changereason        
    
class MotivoRechazo(models.Model):
    codigo = models.CharField(max_length=2, unique=True)
    descripcion = models.CharField(max_length=255)

    def __str__(self):
        return self.descripcion
    

    
class Task(models.Model):
    vin = models.CharField(max_length=100) # vehicle id num - número único de cada vehículo fabricado, por todas las marcas a nivel internacional - regulado por la norma ISO 3833
    project = models.ForeignKey(Project, on_delete=models.CASCADE) # campaña
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    carbrand = models.ForeignKey(CarBrand, on_delete=models.CASCADE)
    carmodel = models.ForeignKey(CarModel, on_delete=models.CASCADE) # la marca se saca con el modelo
    comment = models.TextField(blank=True)

    carimage = models.ImageField(upload_to = 'images/', blank=True, null=True)

    created = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField(null=True, blank=True)
    datecompleted = models.DateTimeField(null=True, blank=True) # fecha en la que el employee termina el trabajo
    datecompleted_manager_approval = models.DateTimeField(null=True, blank=True) # fecha en la que el manager aprueba envío a cliente
    datecompleted_client_approval = models.DateTimeField(null=True, blank=True) # fecha en la que el cliente acepta el envío
    datecompleted_history = models.DateTimeField(null=True, blank=True) # fecha en la que se almacena en el histórico

    employee_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="assigned_user_for_task")
    responsible_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="responsible_user_for_task")

    priority = models.CharField(max_length=1)
    description = models.TextField(blank=True)
    important = models.BooleanField(default=False)
    deniedbyclient = models.BooleanField(default=False)

    # Esto sólo debería rellenarlo el employee una vez vaya completando las tareas. a la hora de entregar, debe validarse que estas están completadas
    windows = models.BooleanField(default=False)
    chassis = models.BooleanField(default=False)
    wheels = models.BooleanField(default=False)
    upholstery = models.BooleanField(default=False)

    #AQUI VA LO BORRADO
    motivo_rechazo_manager = models.CharField(
        max_length=2,
        choices=MotivoRechazo.objects.values_list('codigo', 'descripcion'),
        null=True,
        blank=True,
    )
    comentario_rechazo_manager = models.TextField(blank=True, null=True)

    motivo_rechazo_cliente = models.CharField(
        max_length=2,
        choices=MotivoRechazo.objects.values_list('codigo', 'descripcion'),
        null=True,
        blank=True,
    )

    comentario_rechazo_cliente = models.TextField(blank=True, null=True)

    flag_rechazado = models.BooleanField(default=False)

    def __str__(self):
        #return self.vin + ' - ' + self.project.name + ' - ' + self.description
        return self.vin


class ChangeLog(models.Model):
    task = models.ForeignKey(Task, on_delete=models.CASCADE) # VIN se obtiene con el ID del vehiuclo
    dateofchange = models.DateTimeField(auto_now_add=True) # se setea cuando se genera una fila o se añade una nueva task
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    descripcion_estado = models.TextField(blank=True, null=True)
    changereason = models.CharField(max_length=100, blank=True, null=True)
    comment = models.TextField(blank=True, null=True)
    

    def __str__(self):
        return self.task

class Post(models.Model):
    title = models.CharField(max_length=250)
    description = models.TextField()
    image = models.FileField(blank=True)

    def __str__(self):
        return self.title
    


class PostImage(models.Model):
    task = models.ForeignKey(Task, default=None, on_delete=models.CASCADE)
    images = models.FileField(upload_to = 'images/')

    def __str__(self):
        return self.task.vin

sgmaq/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.contrib.auth import login, logout, authenticate
from django.db import IntegrityError
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.db.models import Q  # Import the Q object
from django.db.models import Count, Prefetch
from django.db import connection
from .decorators import unauthenticated_user, allowed_user
import plotly.express as px
import os
from django.conf import settings

from .models import Project
from .models import Client
from .models import CarBrand
from .models import CarModel
from .models import MotivoRechazo
from .models import PostImage
from .models import ChangeReason
from .models import ChangeLog
from .models import Task


from .forms import EmployeeTaskForm
from .forms import TaskUploadImage
from .forms import PostImageForm
from .forms import TaskDeliveryClientForm
from .forms import TaskFormRechazoManager
from .forms import TaskFormRechazoCliente
from .forms import UploadFileForm

from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph
from reportlab.platypus import Image as ImageReportlab
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import inch

from datetime import datetime
import pandas as pd
from django.core.exceptions import ObjectDoesNotExist


def index(request):
    return render(request, 'global/index.html')

def about(request):
    return render(request, 'global/about.html')

@unauthenticated_user
def signup(request):
    if request.method == 'GET':
        return render(request, 'global/signup.html', {"form": UserCreationForm})
    else:

        if request.POST["password1"] == request.POST["password2"]:
            try:
                user = User.objects.create_user(
                    request.POST["username"], password=request.POST["password1"])
                user.save()
                login(request, user)
                return redirect('index')
            except IntegrityError:
                return render(request, 'global/signup.html', {"form": UserCreationForm, "error": "Username already exists."})

        return render(request, 'global/signup.html', {"form": UserCreationForm, "error": "Passwords did not match."})

@unauthenticated_user
def signin(request):
    if request.method == 'GET':
        return render(request, 'global/signin.html', {"form": AuthenticationForm})
    else:
        user = authenticate(
            request, username=request.POST['username'], password=request.POST['password'])
        if user is None:
            return render(request, 'global/signin.html', {"form": AuthenticationForm, "error": "Username or password is incorrect."})

        login(request, user)
        return redirect('index')
    
@allowed_user(allowed_roles=['admin', 'manager', 'employee', 'customer'])
def signout(request):
    logout(request)
    return redirect('index')

@login_required
@allowed_user(allowed_roles=['admin', 'manager', 'employee'])
def tasks(request):
    tasks = Task.objects.filter(Q(employee_user=request.user), datecompleted__isnull=True)
    pending_tasks_count = Task.objects.filter(datecompleted__isnull=True).count() # se mostrará para admins y managers
    pending_tasks_per_user = Task.objects.filter(datecompleted__isnull=True).values('employee_user_id__username').annotate(total=Count('id')) # 
    
    # Obtener la descripción del motivo de rechazo para cada tarea
    for task in tasks:
        if task.motivo_rechazo_manager:
            motivo_rechazo_id = task.motivo_rechazo_manager
            motivo_rechazo_desc = MotivoRechazo.objects.get(codigo=motivo_rechazo_id).descripcion
            task.motivo_rechazo_desc = motivo_rechazo_desc  # Añadir el campo de descripción al objeto de tarea


    return render(request, 'tasks/tasks.html', {
        'tasks': tasks,
        'pending_tasks_count': pending_tasks_count,
        'pending_tasks_per_user': pending_tasks_per_user
    })

@login_required
def task_search(request):
    # filtramos las tareas por usuario, por pendiente y por id (patente)
    query = request.GET.get('q')
    tasks = Task.objects.filter(employee_user=request.user, datecompleted__isnull=True, vin__icontains=query)
    return render(request, 'tasks/tasks.html', {
        'tasks': tasks
    })

@login_required
def upload_file(request):
    if request.method == 'POST':
        file = request.FILES.get('file')
        try:
            # Leer el archivo Excel usando pandas
            df = pd.read_excel(file)

            # Convertir las columnas de fecha a cadenas
            if 'deadline' in df.columns:
                df['deadline'] = df['deadline'].astype(str)

            # Procesar cada fila por separado
            results = []
            for index, row in df.iterrows():
                try:
                    vin = row['vin']
                    project_name = row['proyecto']
                    client_name = row['cliente']
                    carbrand = row['carbrand']
                    carmodel = row['carmodel']
                    comment = row['comment'] if pd.notnull(row['comment']) else None
                    created = datetime.now()  # Fecha y hora actual
                    deadline = row['deadline'] if pd.notnull(row['deadline']) else None
                    employee_user = row['employee']
                    responsible_user = row['responsible']
                    priority = row['priority']
                    description = row['description'] if pd.notnull(row['description']) else None
                    important = row['important']
                    deniedbyclient = False
                    windows = False
                    chassis = False
                    wheels = False
                    upholstery = False
                    flag_rechazado = False

                    # Validar el campo VIN
                    if Task.objects.filter(vin=vin).exists():
                        raise IntegrityError(f'El VIN "{vin}" ya existe en la base de datos.')
                    
                    # Validar el campo proyecto
                    try:
                        project = Project.objects.get(name=project_name)
                    except ObjectDoesNotExist:
                        raise ValueError(f'El proyecto "{project_name}" no existe en la base de datos.')
                    
                    # Validar el campo cliente
                    try:
                        client = Client.objects.get(name=client_name)
                    except ObjectDoesNotExist:
                        raise ValueError(f'El cliente "{client_name}" no existe en la base de datos.')

                    # Validar el campo carbrand
                    try:
                        car_brand = CarBrand.objects.get(brandname=carbrand)
                    except ObjectDoesNotExist:
                        raise ValueError(f'La marca de coches "{carbrand}" no existe en el sistema.')

                    # Validar el campo carmodel
                    try:
                        car_model = CarModel.objects.get(model=carmodel)
                    except ObjectDoesNotExist:
                        raise ValueError(f'El modelo "{carmodel}" no existe en el sistema.')

                    # Validar que la relación entre marca y modelo 
                    
                    # Validar campos de usuario
                    try:
                        responsible_user_info = User.objects.get(username=responsible_user)
                    except ObjectDoesNotExist:
                        raise ValueError(f'El usuario "{responsible_user}" no existe en el sistema.')

                    try:
                        employee_user_info = User.objects.get(username=employee_user)
                    except ObjectDoesNotExist:
                        raise ValueError(f'El usuario "{employee_user}" no existe en el sistema.')

                    # Validar del campo prioridad
                    if priority != 1 and priority != 0:
                        raise ValueError(f'El valor del campo "prioridad" en la fila {index + 2} no es válido. Sólo se permiten los valores 0 y 1.')

                    # Crear una nueva instancia de Task usando el método create
                    task = Task.objects.create(
                        vin=vin,
                        project=project,
                        client=client,
                        carbrand=car_brand,
                        carmodel=car_model,
                        comment=comment,
                        created=created,
                        deadline=deadline,
                        employee_user=employee_user_info,
                        responsible_user=responsible_user_info,
                        priority=priority,
                        description=description,
                        important=important,
                        deniedbyclient=deniedbyclient,
                        windows=windows,
                        chassis=chassis,
                        wheels=wheels,
                        upholstery=upholstery,
                        flag_rechazado=flag_rechazado
                    )

                    # Create changelog entry
                    ChangeLog.objects.create(
                        task=task,
                        dateofchange=created,
                        user=request.user,
                        descripcion_estado="Alta en el sistema",
                        changereason="Alta en el sistema",
                        comment="Alta en el sistema desde carga de fichero"
                    )

sgmaq/templates/tasks/dashboard.html
{% extends 'layouts/base.html' %}
{% block content %}

<main class="container py-4">
  <div class="text-center mb-4">
    <h1>Dashboard</h1>
  </div>

  {% load project_custom_tags %}

  <!-- PERFILES ADMINISTRADORES Y DE GESTION -->
  {% if request.user|has_group:"manager" or request.user|has_group:"admin" %}

    <div class="alert alert-info">
      <p>You are an admin/manager. You can see the dashboard page.</p>
    </div>

    <div class="card shadow-sm border-0 mb-4">
      <div class="card-header bg-dark text-white">
        <h5 class="mb-0">Número de altas en el sistema por mes</h5>
      </div>
      <div class="card-body bg-light text-dark">
        {{ chart|safe }}
      </div>
    </div>

    <div class="card shadow-sm border-0 mb-4">
      <div class="card-header bg-dark text-white">
        <h5 class="mb-0">Número de rechazos en el sistema por mes</h5>
      </div>
      <div class="card-body bg-light text-dark">
        {{ chart_rechazos_por_mes|safe }}
      </div>
    </div>

    <div class="card shadow-sm border-0 mb-4">
      <div class="card-header bg-dark text-white">
        <h5 class="mb-0">Número de rechazos en el sistema</h5>
      </div>
      <div class="card-body bg-light text-dark">
        {{ chart_rechazos_por_empleado|safe }}
      </div>
    </div>

  {% endif %}
</main>

{% endblock %}

sgmaq/templates/tasks/task_delivery.html
{% extends 'layouts/base.html' %}
{% block content %}

<div class="container mt-4">
  
  {% if error %}
    <div class="alert alert-danger">{{ error }}</div>
  {% endif %}

  <ul class="nav nav-pills mb-4" id="pills-tab" role="tablist">
    <li class="nav-item" role="presentation">
      <button class="nav-link active" id="pills-home-tab" data-bs-toggle="pill" data-bs-target="#pills-home" type="button" role="tab" aria-controls="pills-home" aria-selected="true">Estado actual</button>
    </li>
    <li class="nav-item" role="presentation">
      <button class="nav-link" id="pills-profile-tab" data-bs-toggle="pill" data-bs-target="#pills-profile" type="button" role="tab" aria-controls="pills-profile" aria-selected="false">Detalle de tarea</button>
    </li>
    <li class="nav-item" role="presentation">
      <button class="nav-link" id="pills-contact-tab" data-bs-toggle="pill" data-bs-target="#pills-contact" type="button" role="tab" aria-controls="pills-contact" aria-selected="false">Histórico</button>
    </li>
    <li class="nav-item" role="presentation">
      <button class="nav-link" id="pills-report-tab" data-bs-toggle="pill" data-bs-target="#pills-report" type="button" role="tab" aria-controls="pills-report" aria-selected="false">Reporte fotográfico</button>
    </li>
  </ul>
  
  <div class="tab-content" id="pills-tabContent">
    <div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab" tabindex="0">
      <div class="card shadow-sm border-0 mb-4">
        <div class="card-header bg-dark text-white">
          <div class="d-flex justify-content-between align-items-center">
            <h4 class="mb-0">VIN: {{ task.vin }}</h4>
            <a href="{% url 'tasks' %}" class="btn btn-warning text-dark">Volver</a>
          </div>
        </div>
        <div class="card-body bg-light text-dark">
          <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="row">
              <div class="col-md-6">
                <h5>Actualizar tarea</h5>
                {% for field in form %}
                  <div class="form-group mb-3">
                    {% if field.field.widget.input_type == "checkbox" %}
                      <div class="form-check">
                        {{ field }}
                        {{ field.label_tag }}
                      </div>
                    {% else %}
                      <div class="d-flex justify-content-between align-items-center">
                        {{ field.label_tag }}
                        {{ field }}
                      </div>
                    {% endif %}
                  </div>
                {% endfor %}
              </div>
            </div>
          </form>
          <div class="row">
            <div class="col">
              <div class="d-flex">
                <form id="complete-task-form" action="{% url 'complete_task' task.id %}" method="POST">
                  {% csrf_token %}
                  <button id="complete-task-button" type="submit" class="btn btn-warning mr-2">Entregar</button>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="tab-pane fade" id="pills-profile" role="tabpanel" aria-labelledby="pills-profile-tab" tabindex="0">
      <div class="container">
        <div class="row">
          <div class="col-md-6 mb-4">
            <div class="card shadow-sm border-0">
              <div class="card-header bg-dark text-white">
                <h5 class="mb-0">Detalle de Tarea</h5>
              </div>
              <div class="card-body bg-light text-dark">
                <table class="table table-sm table-striped">
                  <tbody>
                    <tr>
                      <th scope="row">VIN</th>
                      <td>{{ task.vin }}</td>
                    </tr>
                    <tr>
                      <th scope="row">Proyecto</th>
                      <td>{{ task.project }}</td>
                    </tr>
                    <tr>
                      <th scope="row">Cliente</th>
                      <td>{{ task.client }}</td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
          <div class="col-md-6 mb-4">
            <div class="card shadow-sm border-0">
              <div class="card-header bg-dark text-white">
                <h5 class="mb-0">Información Adicional</h5>
              </div>
              <div class="card-body bg-light text-dark">
                <table class="table table-sm table-striped">
                  <tbody>
                    <tr>
                      <th scope="row">Comentario</th>
                      <td>{{ task.comment }}</td>
                    </tr>
                    <tr>
                      <th scope="row">Fecha Límite</th>
                      <td>{{ form.deadline.label }} {{ form.deadline }}</td>
                    </tr>
                    <tr>
                      <th scope="row">Fecha Completada</th>
                      <td>{{ task.datecompleted }}</td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-6 mb-4">
            <div class="card shadow-sm border-0">
              <div class="card-header bg-dark text-white">
                <h5 class="mb-0">Usuarios</h5>
              </div>
              <div class="card-body bg-light text-dark">
                <table class="table table-sm table-striped">
                  <tbody>
                    <tr>
                      <th scope="row">Usuario Asignado</th>
                      <td>{{ task.employee_user }}</td>
                    </tr>
                    <tr>
                      <th scope="row">Usuario Responsable</th>
                      <td>{{ task.responsible_user }}</td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
          <div class="col-md-6 mb-4">
            <div class="card shadow-sm border-0">
              <div class="card-header bg-dark text-white">
                <h5 class="mb-0">Otros</h5>
              </div>
              <div class="card-body bg-light text-dark">
                <table class="table table-sm table-striped">
                  <tbody>
                    <tr>
                      <th scope="row">Prioridad</th>
                      <td>{{ task.priority }}</td>
                    </tr>
                    <tr>
                      <th scope="row">Descripción</th>
                      <td>{{ task.description }}</td>
                    </tr>
                    <tr>
                      <th scope="row">Importante</th>
                      <td>
                        <input type="checkbox" id="important" name="important" value="{{ task.important }}" {% if task.important %}checked{% endif %}>
                      </td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    
    <div class="tab-pane fade" id="pills-contact" role="tabpanel" aria-labelledby="pills-contact-tab" tabindex="0">
      <div class="container">
        <div class="card shadow-sm border-0 mb-4">
          <div class="card-header bg-dark text-white">
            <h5 class="mb-0">Histórico de la tarea</h5>
          </div>
          <div class="card-body bg-light text-dark">
            <table class="table table-striped">
              <thead class="bg-dark text-white">
                <tr>
                  <th>Fecha de Cambio</th>
                  <th>Usuario</th>
                  <th>Descripción estado</th>
                  <th>Motivo rechazo</th>
                  <th>Comentario cambio estado</th>
                </tr>
              </thead>
              <tbody>
                {% for entry, user in history %}
                <tr>
                  <td>{{ entry.dateofchange }}</td>
                  <td>{{ user.username }}</td>
                  <td>{{ entry.descripcion_estado }}</td>
                  <td>{{ entry.changereason }}</td>
                  <td>{{ entry.comment }}</td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
    
    <div class="tab-pane fade" id="pills-report" role="tabpanel" aria-labelledby="pills-report-tab" tabindex="0">
      <div class="container">
        <div class="card shadow-sm border-0 mb-4">
          <div class="card-header bg-dark text-white">
            <h5 class="mb-0">Reporte fotográfico</h5>
          </div>
          <div class="card-body bg-light text-dark">
            <form id="image-upload-form" method="post" enctype="multipart/form-data">
              {% csrf_token %}
              <div class="form-group mb-3">
                <input type="file" name="images" class="form-control" multiple>
              </div>
              <button id="upload-button" class="btn btn-warning text-dark" type="submit">Upload Image</button>
            </form>
            {% if images %}
            <div id="carouselExample" class="carousel slide mt-4">
              <div class="carousel-inner">
                {% for image in images %}
                <div class="carousel-item {% if forloop.first %}active{% endif %}">
                  <img src="{{ image.images.url }}" class="d-block w-100" alt="...">
                </div>
                {% endfor %}
              </div>
              <button class="carousel-control-prev" type="button" data-bs-target="#carouselExample" data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Previous</span>
              </button>
              <button class="carousel-control-next" type="button" data-bs-target="#carouselExample" data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Next</span>
              </button>
            </div>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </div>

  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  
  <script>
    $(document).ready(function() {
      function checkTaskCompletion() {
        var allChecked = $('#id_windows').is(':checked') &&
                         $('#id_chassis').is(':checked') &&
                         $('#id_wheels').is(':checked') &&
                         $('#id_upholstery').is(':checked');
        
        if (allChecked) {
          $('#complete-task-button').removeClass('disabled').prop('disabled', false);
        } else {
          $('#complete-task-button').addClass('disabled').prop('disabled', true);
        }
      }
  
      $('input[type="checkbox"]').change(function() {
        var checkbox = $(this);
        var isChecked = checkbox.is(':checked');
        var csrfToken = '{{ csrf_token }}';
        var fieldName = checkbox.attr('name');
  
        $.ajax({
          url: "{% url 'task_delivery' task.id %}",
          type: "POST",
          data: {
            'csrfmiddlewaretoken': csrfToken,
            'field': fieldName,
            'value': isChecked
          },
          success: function(response) {
            console.log('Checkbox updated successfully');
            checkTaskCompletion();
          },
          error: function(xhr, status, error) {
            console.log('Error updating checkbox: ' + error);
          }
        });
      });
  
      checkTaskCompletion();
    });
  </script>
  
  <script>
    $(document).ready(function() {
      $('#upload-button').click(function(event) {
        event.preventDefault();
        var formData = new FormData($('#image-upload-form')[0]);
        $.ajax({
          url: "{% url 'upload_image' task.id %}",
          type: 'POST',
          data: formData,
          processData: false,
          contentType: false,
          headers: {
            'X-CSRFToken': '{{ csrf_token }}'
          },
          success: function(response) {
            if (response.status === 'success') {
              alert('La imagen se ha subido correctamente');
              location.reload();
            } else {
              alert('Error subiendo la imagen: ' + JSON.stringify(response.errors));
            }
          },
          error: function(xhr, status, error) {
            alert('Error: ' + error);
          }
        });
      });
    });
  </script>
</div>

{% endblock %}